### ISSUE TITLE
Does not work on Windows 8.1

### ISSUE THREAD

**Issue by Boscop** [purescript/psc-package#81] opened 2018-01-20 21:35 UTC
After running into [this issue](https://github.com/joneshf/node-psc-package-bin/issues/1) I installed psc-package.exe from the releases here. But it doesn't create the psc-package.json file:
```
> psc-package --help
Usage: psc-package COMMAND
  Manage package dependencies

Available options:
  --version                Show the version number
  -h,--help                Show this help text

Available commands:
  init                     Create a new psc-package.json file
  update                   Install or update package dependencies
  uninstall                Uninstall the named package
  install                  Install the named package
  build                    Update dependencies and compile the current package
  repl                     Open an interactive environment for PureScript
  dependencies             List all (transitive) dependencies for the current
                           package
  sources                  List all (active) source paths for dependencies
  available                List all packages available in the package set
  updates                  Check all packages in the package set for new
                           releases
  verify-set               Verify that the packages in the package set build
                           correctly
  verify                   Verify the named package

psc-package 0.2.5

> psc-package init
Initializing new project in current directory
psc-package: purs: createProcess: does not exist (No such file or directory)
```
But `purs` is in `PATH`:
```
> where purs
C:\Users\me\AppData\Roaming\npm\purs
C:\Users\me\AppData\Roaming\npm\purs.cmd

> purs --help
Usage: purs.bin COMMAND
  The PureScript compiler and tools

Available options:
  --version                Show the version number
  -h,--help                Show this help text

Available commands:
  bundle                   Bundle compiled PureScript modules for the browser
  compile                  Compile PureScript source files
  docs                     Generate Markdown documentation from PureScript
                           source files
  hierarchy                Generate a GraphViz directed graph of PureScript type

                           classes
  ide                      Start or query an IDE server process
  publish                  Generates documentation packages for upload to
                           Pursuit
  repl                     Enter the interactive mode (PSCi)

purs 0.11.7
```

**Comment by hdgarrood** [comment] 2018-01-20 21:47
I think this is a duplicate of #34. For now, I think you can work around this by downloading the purs binary and placing it on your PATH manually, in front of npm's PATH directory for binaries.

**Closed as completed by hdgarrood** 2018-01-20 21:47 UTC

**Comment by Boscop** [comment] 2018-01-20 22:06
Thanks, that worked :)
